#
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
FROM quay.io/ascend/cann:8.5.1-a3-ubuntu22.04-py3.11

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=${HTTP_PROXY} \
    https_proxy=${HTTPS_PROXY} \
    HTTP_PROXY=${HTTP_PROXY} \
    HTTPS_PROXY=${HTTPS_PROXY} \
    no_proxy=${NO_PROXY} \
    NO_PROXY=${NO_PROXY}

WORKDIR /root
ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

RUN if [ -n "$HTTP_PROXY" ]; then \
      echo "Acquire::http::Proxy \"$HTTP_PROXY\";" > /etc/apt/apt.conf.d/99proxy; \
      echo "Acquire::https::Proxy \"$HTTPS_PROXY\";" >> /etc/apt/apt.conf.d/99proxy; \
    fi

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
        gcc g++ cmake libnuma-dev wget git curl jq vim \
        build-essential patchelf tmux net-tools htop nano iputils-ping \
        autoconf automake libatlas-base-dev libgoogle-glog-dev libbz2-dev libc-ares2 \
        libleveldb-dev liblmdb-dev libprotobuf-dev libsnappy-dev libtool nasm protobuf-compiler pkg-config unzip sox \
        libsndfile1 libpng-dev libhdf5-dev gfortran rapidjson-dev ninja-build libedit-dev rsync && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Setting env
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "aarch64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/linux/aarch64:$LD_LIBRARY_PATH; \
    elif [ "$ARCH" = "x86_64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/x86_64-linux/devlib/linux/x86_64/:$LD_LIBRARY_PATH; \
    fi && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh
# Setting pip & git config. Global config (set once, persists across subsequent RUN layers)
ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
RUN pip config set global.index-url ${PIP_INDEX_URL} && \
    git config --global http.sslverify false && \
    git config --global http.postBuffer 2147483648 && \
    git config --global user.email "temp@example.com" && \
    git config --global user.name "temp"
WORKDIR /root

COPY . /root/Relax
RUN pip install --upgrade pip packaging setuptools==80.10.2 && \
    pip install torch==2.9.0 && \
    pip install numpy==1.26.0
    # build torch_npu
RUN pip install pyyaml && \
    git clone https://gitcode.com/Ascend/pytorch.git /root/pytorch && \
    cd /root/pytorch && \
    git checkout v2.9.0-7.3.0 && \
    git cherry-pick -n f495de675bce38a2fa21edbf067b73d2a5f26733 && \
    bash ci/build.sh --python=3.11 && \
    pip install dist/torch_npu-2.9.0*.whl
RUN cd /root && rm -rf /root/pytorch && \
    pip install triton-ascend==3.2.0 && \
    pip install tensordict==0.10.0 pyvers==0.1.0 --no-deps && \
    pip install "transferqueue @ git+https://github.com/redai-infra/TransferQueue.git" --no-deps -i https://pypi.tuna.tsinghua.edu.cn/simple

    # Clone Megatron-LM, MindSpeed, MindSpeed-Bridge, Megatron-Bridge and install
RUN git clone https://gitcode.com/ascend/MindSpeed.git /root/MindSpeed && \
    git clone https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM && \
	git clone https://gitcode.com/ascend/MindSpeed-Bridge.git /root/MindSpeed-Bridge && \
    git clone https://github.com/NVIDIA-NeMo/Megatron-Bridge.git /root/Megatron-Bridge

RUN cd /root/MindSpeed && git checkout core_r0.16.0 && pip install -r requirements.txt && pip install -e . && \
    cd /root/Megatron-LM && git checkout core_v0.16.1 && pip install -e . --no-build-isolation && \
    cd /root/Megatron-Bridge && git checkout v0.3.1 && \
    cd /root/MindSpeed-Bridge && git checkout 3655c07cbcc9 && pip install -r requirements.txt && bash tools/install_auto.sh

# Patch Megatron-LM, MindSpeed, MindSpeed-Bridge
RUN cd /root/MindSpeed && \
    patch -p1 < /root/Relax/docker/npu_patch/mindspeed.patch && \
    cd /root/Megatron-Bridge && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron-bridge.patch && \
    cd /root/Megatron-LM && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron.patch && \
    cd /root/MindSpeed-Bridge && \
    patch -p1 < /root/Relax/docker/npu_patch/mindspeed-bridge.patch

# Copy MindSpeed-Bridge, Megatron-Bridge into Megatron-LM
RUN cp -r /root/MindSpeed-Bridge/mindspeed_bridge /root/Megatron-LM/ && \
    cp -r /root/Megatron-Bridge/src/megatron/bridge /root/Megatron-LM/megatron/ && \
    cd /root && rm -rf /root/MindSpeed-Bridge && rm -rf /root/Megatron-Bridge 

# Install sglang
RUN git clone https://github.com/sgl-project/sglang.git /root/sglang && \
    cd /root/sglang && git checkout v0.5.10 && \
    mv python/pyproject.toml python/pyproject.toml.backup && \
    mv python/pyproject_npu.toml python/pyproject.toml && \
    pip install -e "python[srt_npu]" --constraint <(echo "torch==2.9.0") && \
    # [NPU] Fix Qwen3.5 inference acc.
    git stash  && \
    git fetch origin pull/23815/head:pr-23815 && \
    git checkout pr-23815

# Install sgl-kernle-npu
RUN git clone https://github.com/sgl-project/sgl-kernel-npu /root/sgl-kernel-npu && \
    cd /root/sgl-kernel-npu && git checkout 2026.04.15.rc3 && \
    # Adapt tms for colocate train.
    git cherry-pick -n 23519771d347 --no-gpg-sign && \
    patch -p1 < /root/Relax/docker/npu_patch/torch-memory-saver.patch  && \
    bash build.sh -a kernels && bash build.sh -a memory-saver && \
    pip install output/*.whl && \
    cd /root && rm -rf /root/sgl-kernel-npu 

# Install Relax
RUN cd /root/Relax && pip install -e .

RUN pip install ray==2.55.1

#Clean cache
RUN pip cache purge && \
    rm -rf /tmp/*
